# Generated by Django 5.1.5 on 2025-01-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='Email_Address',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='Full_Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='Message',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='Subject',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_address',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_contact',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_password',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_subject',
            field=models.TextField(default='default_value_here', max_length=100),
        ),
    ]
