# Generated by Django 5.0.1 on 2025-02-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='feedback_files/'),
        ),
    ]
