# Generated by Django 5.0.6 on 2025-03-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
