# Generated by Django 5.0.6 on 2025-03-18 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_contact_us_email_address_and_more'),
        ('userapp', '0004_alter_feedback_file_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('prediction_id', models.AutoField(primary_key=True, serialize=False)),
                ('predicted_class', models.CharField(max_length=100, null=True)),
                ('prediction_accuracy', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('input_image', models.FileField(blank=True, null=True, upload_to='media/')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.usermodel')),
            ],
            options={
                'db_table': 'prediction_results',
            },
        ),
    ]
