# Generated by Django 5.0.6 on 2025-03-18 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_predictionresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictionresult',
            name='input_image',
        ),
        migrations.RemoveField(
            model_name='predictionresult',
            name='user',
        ),
    ]
