# Generated by Django 5.0.6 on 2025-03-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_remove_predictionresult_input_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=255)),
                ('predicted_result', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=100)),
                ('model_accuracy', models.FloatField()),
                ('uploaded_image_base64', models.TextField()),
                ('segmented_image_base64', models.TextField()),
                ('grayscale_image_base64', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PredictionResult',
        ),
    ]
